/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcialdoslii;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Sil y Pato
 */
public class dlgArchivo extends javax.swing.JDialog implements KeyListener{

    /**
     * Creates new form dlgArchivo
     */
    public dlgArchivo(java.awt.Frame parent, boolean modal, String[] lista, TipoDialogoEnum tipo) {
        super(parent, modal);
        this.listaArchivos = lista;
        this.tipoDialogo = tipo;
        this.dialogoCancelado = false;
        initComponents();
        this.setComboEditable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbArchivos = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(cmbArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(cmbArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (String listaArchivo : listaArchivos)
        {
            this.cmbArchivos.addItem(listaArchivo);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dialogoCancelado = true;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    public String getArchivoSeleccionado()
    {
        String retorno;
        
        if(this.cmbArchivos.getSelectedItem() == null)
        {
            retorno = "";
        }
        else
        {
            retorno = this.cmbArchivos.getSelectedItem().toString();
        }
        
        return retorno;
    }
    
    private void setComboEditable()
    {
        this.cmbArchivos.getEditor().getEditorComponent().addKeyListener(this);

        if(this.tipoDialogo.equals(TipoDialogoEnum.ABRIR))
        {
            this.cmbArchivos.setEditable(false);
        }
        else if(this.tipoDialogo.equals(TipoDialogoEnum.GUARDAR))
        {
            this.cmbArchivos.setEditable(true);
            this.cmbArchivos.setSelectedItem("");
        }
    }

    public boolean isDialogoCancelado()
    {
        return dialogoCancelado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbArchivos;
    // End of variables declaration//GEN-END:variables
    private String[] listaArchivos;
    private TipoDialogoEnum tipoDialogo;
    private boolean dialogoCancelado;

    @Override
    public void keyTyped(KeyEvent e)
    {
        switch(e.getKeyChar())
        {
            case KeyEvent.VK_ESCAPE:
                this.dialogoCancelado = true;
                this.setVisible(false);
                break;
            case KeyEvent.VK_ENTER:
                this.setVisible(false);
                break;
        }
    }

    @Override
    public void keyPressed(KeyEvent e)
    {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e)
    {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
