/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcialdoslii;

/**
 *
 * @author Sil y Pato
 */
public class dlgNuevoAhorcado extends javax.swing.JDialog
{

    /**
     * Creates new form dlgNuevoAhorcado
     */
    public dlgNuevoAhorcado(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.iniciarComboDificultad();
        this.iniciarComboMascara();
        this.llenarComboFallos(this.cmbDificultad.getSelectedItem().toString());
        this.llenarComboAyuda(this.cmbFallosMaximos.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDificultad = new javax.swing.JLabel();
        cmbDificultad = new javax.swing.JComboBox<>();
        separador = new javax.swing.JSeparator();
        lblMascara = new javax.swing.JLabel();
        cmbMascara = new javax.swing.JComboBox<>();
        lblFallosMaximos = new javax.swing.JLabel();
        cmbFallosMaximos = new javax.swing.JComboBox<>();
        lblMuestraAyuda = new javax.swing.JLabel();
        cmbMuestraAyuda = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Juego Ahorcado");

        lblDificultad.setText("Dificultad:");

        cmbDificultad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDificultadItemStateChanged(evt);
            }
        });

        lblMascara.setText("Máscara:");

        lblFallosMaximos.setText("Fallos Máximos:");

        lblMuestraAyuda.setText("Muestra Ayuda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDificultad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFallosMaximos)
                                    .addComponent(lblMascara)
                                    .addComponent(lblMuestraAyuda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbFallosMaximos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbMascara, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbMuestraAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDificultad)
                    .addComponent(cmbDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMascara)
                    .addComponent(cmbMascara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFallosMaximos)
                    .addComponent(cmbFallosMaximos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMuestraAyuda)
                    .addComponent(cmbMuestraAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDificultadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDificultadItemStateChanged
        this.llenarComboFallos(this.cmbDificultad.getSelectedItem().toString());
        this.llenarComboAyuda(this.cmbFallosMaximos.getSelectedItem().toString());
    }//GEN-LAST:event_cmbDificultadItemStateChanged
    
    private void iniciarComboDificultad()
    {
        this.cmbDificultad.addItem(DificultadPalabraEnum.FACIL.toString());
        this.cmbDificultad.addItem(DificultadPalabraEnum.DIFICIL.toString());
    }
    
    private void iniciarComboMascara()
    {
        for (char i = 33; i < 127; i++)
        {
            if(!Character.isLetterOrDigit(i))
            {
                this.cmbMascara.addItem(Character.toString(i));
            }
        }
        
        this.cmbMascara.setSelectedItem("*");
    }
    
    private void llenarComboFallos(String dificultad)
    {
        this.cmbFallosMaximos.removeAllItems();
        
        for (int i = JuegoAhorcado.getFallosMinimosPermitidos() ; i < JuegoAhorcado.getFallosMinimosPermitidos() * (3 - DificultadPalabraEnum.valueOf(dificultad).ordinal()); i++)
        {
            this.cmbFallosMaximos.addItem(Integer.toString(i));
        }
        
        this.cmbFallosMaximos.setSelectedItem(Integer.toString(JuegoAhorcado.getFallosMinimosPermitidos() * (2 - DificultadPalabraEnum.valueOf(dificultad).ordinal())));
    }
    
    private void llenarComboAyuda(String fallosMaximos)
    {
        int cantidadFallos = Integer.parseInt(fallosMaximos);
        
        this.cmbMuestraAyuda.removeAllItems();

        for (int i = 0; i < cantidadFallos; i++)
        {
            this.cmbMuestraAyuda.addItem(Integer.toString(i));
        }
        
        this.cmbMuestraAyuda.setSelectedItem(String.valueOf(cantidadFallos / 2));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDificultad;
    private javax.swing.JComboBox<String> cmbFallosMaximos;
    private javax.swing.JComboBox<String> cmbMascara;
    private javax.swing.JComboBox<String> cmbMuestraAyuda;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JLabel lblFallosMaximos;
    private javax.swing.JLabel lblMascara;
    private javax.swing.JLabel lblMuestraAyuda;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
